appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WWpmeNCdbKBMRjns7D9PJxktO4GK1gZ6WPiJHyjKn7c71EO02xNKFwSQASBKc2UHs0J9LHxosBzmc1VlEhNNR6VIok+oCiK6fdmZKohXnTEv3hD/jveF9FBTH3GCu6I3CT0srgQR5dcFIX0QZrih7RF6UwMgua2KsRqOU/EBsmiXIA4t93cC0buqill7BqsfIYcdYYtthDP43XXbq2RIlKA4bvoHI3N2VzOvLsyvPd2SOiwmTHOj4mkmdu7KA7C9Ck0GZ0ozU0WFL9uVbPy1/1cDONvR8ELqNBIlCrKHrgUYeDQSsmsYfC6f0mwo75IOL1moc120+rGScdLVQas/duCU7845jPqc87RVDJj5WknFxhxTcX3K+jzOlIlQ83vaMK26jBynfEXBdZW7NfsPr8ZmKak6/h2HsbJTBOwrLk8XPAN0sVRArKD9XpkhjZFTxp+gGt+SaPi/LVYYv3trZ7nDXyuAfpGQ1v+IOuisa46h2imoRkFEclMoR4gZIE+oBenezARlDg+RsVbzY6OTUQcwgxr39RbNvn0BXtmqiSz8YKekWhviOtQsC7bbOhPq0nIdYO1ndY6IzE5HwMBlbAmPWHT2RMrSD8Xj9STEBZgN5ZHUBevTsQUEGArpoepuumBvxnYL9P3R3zRvMj0up3QBKizmXF02tqSWa/3fKNg=}
